/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#031522",
        "surface": "#031522",
        "surface-dim": "#031522",
        "surface-bright": "#2a3b49",
        "surface-container-lowest": "#00101c",
        "surface-container-low": "#0b1d2a",
        "surface-container": "#0f212e",
        "surface-container-high": "#1a2c39",
        "surface-container-highest": "#253744",
        "surface-variant": "#253744",
        "on-surface": "#d2e5f7",
        "on-surface-variant": "#c1c6d5",
        "on-background": "#d2e5f7",
        "primary": "#aac7ff",
        "primary-container": "#1475e1",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#aac7ff",
        "on-primary": "#002f64",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#001b3e",
        "on-primary-fixed-variant": "#00458d",
        "inverse-primary": "#005db8",
        "secondary": "#77ff61",
        "secondary-container": "#00e601",
        "secondary-fixed": "#77ff61",
        "secondary-fixed-dim": "#00e601",
        "on-secondary": "#013a00",
        "on-secondary-container": "#016100",
        "on-secondary-fixed": "#002200",
        "on-secondary-fixed-variant": "#015300",
        "tertiary": "#bdc6e0",
        "tertiary-container": "#8791a8",
        "tertiary-fixed": "#d9e2fc",
        "tertiary-fixed-dim": "#bdc6e0",
        "on-tertiary": "#273044",
        "on-tertiary-container": "#202a3d",
        "on-tertiary-fixed": "#121b2e",
        "on-tertiary-fixed-variant": "#3e475b",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#8b919f",
        "outline-variant": "#414753",
        "surface-tint": "#aac7ff",
        "inverse-surface": "#d2e5f7",
        "inverse-on-surface": "#213240",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}
