/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#131312",
        "surface": "#131312",
        "surface-dim": "#131312",
        "surface-bright": "#262422",
        "surface-container-lowest": "#00101c",
        "surface-container-low": "#0b1d2a",
        "surface-container": "#181817",
        "surface-container-high": "#1f1e1c",
        "surface-container-highest": "#2e2c29",
        "surface-variant": "#2e2c29",
        "on-surface": "#efe6d2",
        "on-surface-variant": "#c2b391",
        "on-background": "#efe6d2",
        "primary": "#f0d9a8",
        "primary-container": "#d72a22",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#f0d9a8",
        "on-primary": "#002f64",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#001b3e",
        "on-primary-fixed-variant": "#00458d",
        "inverse-primary": "#005db8",
        "secondary": "#f2d27a",
        "secondary-container": "#e5b85c",
        "secondary-fixed": "#f2d27a",
        "secondary-fixed-dim": "#e5b85c",
        "on-secondary": "#2a1c00",
        "on-secondary-container": "#016100",
        "on-secondary-fixed": "#002200",
        "on-secondary-fixed-variant": "#015300",
        "tertiary": "#bdc6e0",
        "tertiary-container": "#8791a8",
        "tertiary-fixed": "#d9e2fc",
        "tertiary-fixed-dim": "#bdc6e0",
        "on-tertiary": "#273044",
        "on-tertiary-container": "#202a3d",
        "on-tertiary-fixed": "#121b2e",
        "on-tertiary-fixed-variant": "#3e475b",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#8b919f",
        "outline-variant": "#4c4843",
        "surface-tint": "#f0d9a8",
        "inverse-surface": "#efe6d2",
        "inverse-on-surface": "#213240",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}
